In [1]:
import tensorflow as tf
matrix1 = tf.Variable([[11,12,13,14], [15,16,17,18]])

In [2]:
matrix1.shape.as_list()

[2, 4]

In [3]:
reshape1 = tf.reshape(matrix1, shape=[4, 2])
reshape1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])>

In [4]:
reshape1.shape.as_list()

[4, 2]

In [5]:
reshape2 = tf.reshape(matrix1, shape=[1, 8])
reshape2

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[11, 12, 13, 14, 15, 16, 17, 18]])>

In [6]:
reshape2.shape.as_list()

[1, 8]

In [7]:
reshape3 = tf.reshape(matrix1, shape=[8, 1])
reshape3

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18]])>

In [8]:
reshape3.shape.as_list()

[8, 1]

In [9]:
reshape4 = tf.reshape(matrix1, shape=[2, 2, 2])
reshape4

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[11, 12],
        [13, 14]],

       [[15, 16],
        [17, 18]]])>

In [10]:
reshape4.shape.as_list()

[2, 2, 2]

In [11]:
tf.rank(reshape4).numpy()

3

In [12]:
transpose1 = tf.transpose(matrix1)
transpose1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[11, 15],
       [12, 16],
       [13, 17],
       [14, 18]])>

In [13]:
transpose1 == reshape1

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False],
       [False, False],
       [False,  True]])>

In [14]:
transpose2 = tf.transpose(reshape4)
transpose2

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[11, 15],
        [13, 17]],

       [[12, 16],
        [14, 18]]])>