In [1]:
import tensorflow as tf

In [2]:
int_variable = tf.Variable(365, tf.int16)
int_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=365>

In [3]:
tf.rank(int_variable)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [4]:
tf.rank(int_variable).numpy()

0

In [5]:
int_variable.shape

TensorShape([])

In [6]:
int_variable.shape.as_list()

[]

In [8]:
vector_variable = tf.Variable([0.23, 0.42, 0.35], \
                              tf.float32)
vector_variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.23, 0.42, 0.35], dtype=float32)>

In [9]:
tf.rank(vector_variable).numpy()

1

In [10]:
vector_variable.shape.as_list()

[3]

In [11]:
matrix_variable = tf.Variable([[41, 75, 62], \
                               [38, 67, 69]], \
                              tf.int32)
matrix_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[41, 75, 62],
       [38, 67, 69]])>

In [12]:
tf.rank(matrix_variable).numpy()

2

In [13]:
matrix_variable.shape.as_list()

[2, 3]

In [21]:
tensor_variable = tf.Variable([[[41, 75, 62], \
                                  [38, 67, 69]], \
                                  [[51, 70, 65], \
                                    [36, 59, 62]], \
                                   [[95, 78, 98], \
                                    [80, 45, 48]]])
tensor_variable

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[41, 75, 62],
        [38, 67, 69]],

       [[51, 70, 65],
        [36, 59, 62]],

       [[95, 78, 98],
        [80, 45, 48]]])>

In [22]:
tf.rank(tensor_variable).numpy()

3

In [23]:
tensor_variable.shape.as_list()

[3, 2, 3]