In [1]:
import tensorflow as tf

In [6]:
df = tf.data.experimental.make_csv_dataset(r'dataset/drugLibTrain_raw.tsv',
                                           batch_size=1, field_delim='\t')

In [10]:
def prep_ds(ds, shuffle_buffer_size=1024, \
                batch_size=32):
        # Shuffle the dataset
        ds = ds.shuffle(buffer_size=shuffle_buffer_size)
        # Repeat the dataset
        ds = ds.repeat()
        # Batch the dataset
        ds = ds.batch(batch_size)
        return ds

In [11]:
ds = prep_ds(df, batch_size=5)

In [13]:
for x in ds.take(1):\
        print(x)

OrderedDict([('', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[3223],
       [ 404],
       [ 279],
       [1523],
       [ 949]])>), ('urlDrugName', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'nuvaring'],
       [b'restasis'],
       [b'xyrem'],
       [b'glucophage'],
       [b'betamethasone']], dtype=object)>), ('rating', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[ 8],
       [ 1],
       [ 9],
       [ 8],
       [10]])>), ('effectiveness', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Highly Effective'],
       [b'Ineffective'],
       [b'Highly Effective'],
       [b'Considerably Effective'],
       [b'Highly Effective']], dtype=object)>), ('sideEffects', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'No Side Effects'],
       [b'Moderate Side Effects'],
       [b'Moderate Side Effects'],
       [b'No Side Effects'],
       [b'No Side Effects']], dtype=object)>), ('condition', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
arr

In [17]:
import tensorflow_hub as hub
embedding = "https://tfhub.dev/google/tf2-preview"\
                "/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(embedding, input_shape=[], \
                               dtype=tf.string, \
                               trainable=True)

In [23]:
hub_layer

[<tf.Variable 'Variable:0' shape=(20001, 20) dtype=float32, numpy=
 array([[-0.60565156, -0.01413231,  0.79470503, ...,  0.7346931 ,
         -0.341707  , -0.43011868],
        [-1.2047577 ,  0.21791467,  1.1384295 , ...,  0.74889004,
         -0.41222748,  0.11590002],
        [-1.3130792 , -0.20165846, -1.7422897 , ..., -1.0302742 ,
          1.1531584 ,  0.03316951],
        ...,
        [ 0.13454673, -0.15173355,  0.5368477 , ...,  0.8319293 ,
         -0.61366147, -1.0842572 ],
        [ 0.20673902, -0.1418509 , -0.5856179 , ..., -0.02331898,
          1.6080966 , -0.6525672 ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]], dtype=float32)>]

In [28]:
for x in ds.take(1):\
        print(hub_layer(tf.reshape(x['commentsReview'],[-1])))

tf.Tensor(
[[ 1.3361044  -2.8993206   1.1688447   0.6744903  -2.5855703  -3.8141246
  -1.2645893   1.8495587   1.6932734   1.4106091  -1.5566933   1.3347845
  -0.24358633  0.59959763 -4.6750765   1.656392    4.5005417  -2.0818686
  -1.7888577  -0.5935504 ]
 [ 0.47295803 -0.38856292  0.5133032   0.6471264  -1.3724495  -0.20445769
  -0.8241067  -0.8209772  -0.45733562 -0.42146617 -0.15656942 -0.10436714
   0.68209666 -0.2974076   1.5757813  -0.43703195 -1.2269309   0.08063598
  -0.23382118 -0.42479706]
 [ 0.7247994  -3.325074    1.458296    1.6536409  -1.7424784  -3.0557165
  -2.2355232   2.5066369   2.812075    1.1135345  -1.6780323   2.2412956
  -0.21595728  0.5376175  -4.4306483   2.8813512   4.044093   -2.8532202
  -1.233832   -0.9980966 ]
 [-0.03737091 -0.25487113  0.11871236 -0.10855141 -0.4640345  -0.15187873
  -0.14669526  0.26890415  0.24121     0.25251237 -0.072613    0.35720235
  -0.26417413 -0.14989133 -0.19025597  0.43411335  0.16987789 -0.23216881
  -0.16986977  0.23363844]