In [1]:
import tensorflow as tf

In [7]:
model = tf.keras.Sequential()

In [8]:
model.add(tf.keras.layers.InputLayer(input_shape=(10,), \
                                         name='Input_layer'))

In [9]:
model.add(tf.keras.layers.Dense(5, activation='relu', \
                                    name='First_hidden_layer'))

model.add(tf.keras.layers.Dense(1, name='Output_layer'))

In [10]:
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(10, 5) dtype=float32, numpy=
 array([[-0.03165907, -0.25494388,  0.45992273, -0.2861277 , -0.03693277],
        [ 0.49747747, -0.5075059 , -0.5512922 ,  0.32984537,  0.49139804],
        [-0.164069  , -0.14004421, -0.20256048,  0.36531025, -0.60354114],
        [ 0.59454507,  0.47030634, -0.1262933 ,  0.14139587,  0.49642533],
        [-0.50375235, -0.5135079 ,  0.26323503,  0.04793739,  0.28388   ],
        [ 0.04163212,  0.60092705,  0.3962142 , -0.21635514,  0.2693557 ],
        [-0.42063463, -0.2412391 ,  0.6043454 , -0.36926135, -0.19207671],
        [ 0.15300572,  0.08772653, -0.44346005,  0.3372131 , -0.3395132 ],
        [-0.08928871, -0.47264844, -0.10386312, -0.17210004, -0.464235  ],
        [-0.5185751 ,  0.27240163, -0.14380279, -0.31318754,  0.51776856]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_laye

In [12]:
data = tf.random.normal((40,10))

In [ ]:
data

<tf.Tensor: shape=(40, 10), dtype=float32, numpy=
array([[-1.16236377e+00, -1.30012441e+00, -9.42152679e-01,
        -2.10552168e+00,  2.22916808e-02,  6.64571583e-01,
        -2.73193169e+00,  8.97501528e-01,  7.79124677e-01,
         1.70375669e+00],
       [ 2.14996170e-02,  8.07891548e-01,  9.48564768e-01,
        -1.26122224e+00, -5.00679249e-03,  4.01760489e-01,
        -7.87555099e-01, -2.45719165e-01, -1.01216741e-01,
        -5.15963078e-01],
       [ 6.84732795e-01,  1.93245232e+00, -1.68676186e+00,
        -6.57191634e-01, -1.84345171e-01,  1.67233109e+00,
         6.08671665e-01, -9.57151413e-01, -6.64796472e-01,
        -1.17537946e-01],
       [ 6.54993474e-01, -4.09043193e-01,  3.39014351e-01,
         5.70454955e-01,  8.07900548e-01, -2.61859745e-01,
        -2.92663395e-01,  1.50809371e+00,  5.96634388e-01,
         2.84431309e-01],
       [ 3.42327178e-01, -4.97929826e-02, -7.75425613e-01,
        -8.51385057e-01, -9.43448767e-02, -4.75373596e-01,
         1.10187374e

In [15]:
prediction = model.predict(data)
prediction

array([[-0.23209761],
       [ 0.3052131 ],
       [-2.19468   ],
       [ 0.21150619],
       [ 0.        ],
       [-0.5774652 ],
       [-0.43480963],
       [-1.9365075 ],
       [-1.5074503 ],
       [-0.28133544],
       [-1.7227262 ],
       [-1.4300162 ],
       [-0.41084462],
       [-1.3694923 ],
       [-1.5520709 ],
       [-0.26599878],
       [-1.5087026 ],
       [-0.16476071],
       [-0.11748165],
       [-2.0462303 ],
       [-0.41375428],
       [-1.5234171 ],
       [-0.34563482],
       [ 0.37998396],
       [-1.483769  ],
       [-0.21792664],
       [-0.12467569],
       [-1.4395939 ],
       [ 0.30199334],
       [-1.5085156 ],
       [-0.28909048],
       [ 0.        ],
       [ 0.55592275],
       [-0.41533595],
       [-1.1416702 ],
       [-1.0801475 ],
       [-0.36519253],
       [ 0.7581965 ],
       [-0.14119041],
       [-0.3588317 ]], dtype=float32)